/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AlagoasRouteImport } from './routes/alagoas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ExperienciasRouteImport } from './routes/experiencias'
import { Route as PasseiosRouteImport } from './routes/passeios'
import { Route as PernambucoRouteImport } from './routes/pernambuco'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AlagoasRoute = AlagoasRouteImport.update({
  id: '/alagoas',
  path: '/alagoas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasRoute = ExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const PasseiosRoute = PasseiosRouteImport.update({
  id: '/passeios',
  path: '/passeios',
  getParentRoute: () => rootRouteImport,
} as any)
const PernambucoRoute = PernambucoRouteImport.update({
  id: '/pernambuco',
  path: '/pernambuco',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alagoas': typeof AlagoasRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/contato': typeof ContatoRoute
  '/experiencias': typeof ExperienciasRoute
  '/passeios': typeof PasseiosRoute
  '/pernambuco': typeof PernambucoRoute
  '/sobre': typeof SobreRoute
  '/transfers': typeof TransfersRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alagoas': typeof AlagoasRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/contato': typeof ContatoRoute
  '/experiencias': typeof ExperienciasRoute
  '/passeios': typeof PasseiosRoute
  '/pernambuco': typeof PernambucoRoute
  '/sobre': typeof SobreRoute
  '/transfers': typeof TransfersRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alagoas': typeof AlagoasRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/contato': typeof ContatoRoute
  '/experiencias': typeof ExperienciasRoute
  '/passeios': typeof PasseiosRoute
  '/pernambuco': typeof PernambucoRoute
  '/sobre': typeof SobreRoute
  '/transfers': typeof TransfersRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alagoas'
    | '/auth'
    | '/carrinho'
    | '/contato'
    | '/experiencias'
    | '/passeios'
    | '/pernambuco'
    | '/sobre'
    | '/transfers'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alagoas'
    | '/auth'
    | '/carrinho'
    | '/contato'
    | '/experiencias'
    | '/passeios'
    | '/pernambuco'
    | '/sobre'
    | '/transfers'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alagoas'
    | '/auth'
    | '/carrinho'
    | '/contato'
    | '/experiencias'
    | '/passeios'
    | '/pernambuco'
    | '/sobre'
    | '/transfers'
    | '/_authenticated/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlagoasRoute: typeof AlagoasRoute
  AuthRoute: typeof AuthRoute
  CarrinhoRoute: typeof CarrinhoRoute
  ContatoRoute: typeof ContatoRoute
  ExperienciasRoute: typeof ExperienciasRoute
  PasseiosRoute: typeof PasseiosRoute
  PernambucoRoute: typeof PernambucoRoute
  SobreRoute: typeof SobreRoute
  TransfersRoute: typeof TransfersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alagoas': {
      id: '/alagoas'
      path: '/alagoas'
      fullPath: '/alagoas'
      preLoaderRoute: typeof AlagoasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias': {
      id: '/experiencias'
      path: '/experiencias'
      fullPath: '/experiencias'
      preLoaderRoute: typeof ExperienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passeios': {
      id: '/passeios'
      path: '/passeios'
      fullPath: '/passeios'
      preLoaderRoute: typeof PasseiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pernambuco': {
      id: '/pernambuco'
      path: '/pernambuco'
      fullPath: '/pernambuco'
      preLoaderRoute: typeof PernambucoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlagoasRoute: AlagoasRoute,
  AuthRoute: AuthRoute,
  CarrinhoRoute: CarrinhoRoute,
  ContatoRoute: ContatoRoute,
  ExperienciasRoute: ExperienciasRoute,
  PasseiosRoute: PasseiosRoute,
  PernambucoRoute: PernambucoRoute,
  SobreRoute: SobreRoute,
  TransfersRoute: TransfersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
